version: "3.7"
services:
  
  database:
    image: mongo
    container_name: kilimanjaro-db
    volumes:
      - /kilimanjaro-data:/data/db
  
  backend:
    image: nicococo/kilimanjaro-server
    container_name: kilimanjaro-back
    depends_on:
      - database
  
  frontend:
    image: nicococo/kilimanjaro-client
    container_name: kilimanjaro-front
