version: "3.7"
services:
  
  database:
    image: mongo
    container_name: kilimanjaro-db
    volumes:
      - /kilimanjaro-data:/data/db
  
  server:
    image: nicococo/kilimanjaro-server:dev-compose
    container_name: kilimanjaro-server
    ports:
      - "9001:9001"
    depends_on:
      - database
  
  client:
    image: nicococo/kilimanjaro-client:dev-compose
    container_name: kilimanjaro-client
    ports:
      - "8001:8001"
