version: "3.7"
services:
  
  database:
    image: mongo
    container_name: kilimanjaro-db
    volumes:
      - /kilimanjaro-data:/data/db
    ports:
      - "27017:27017"
  
  server:
    image: nicococo/kilimanjaro-server:dev
    container_name: kilimanjaro-server
    ports:
      - "9001:9001"
    depends_on:
      - database
  
  client:
    image: nicococo/kilimanjaro-client:dev
    container_name: kilimanjaro-client
    ports:
      - "8001:80"
