version: "3.7"
services:

  server:
    image: nicococo/kilimanjaro-server:dev
    container_name: kilimanjaro-server
    volumes:
      - /kilimanjaro-data:/data
    ports:
      - "9001:9001"

  client:
    image: nicococo/kilimanjaro-client:dev
    container_name: kilimanjaro-client
    ports:
      - "8001:80"
