version: "3.7"
services:

  server:
    image: nicococo/kilimanjaro-service:dev
    container_name: kilimanjaro-service
    volumes:
      - /kilimanjaro-data:/data
    ports:
      - "9001:9001"

  client:
    image: nicococo/kilimanjaro-app:dev
    container_name: kilimanjaro-app
    ports:
      - "8001:80"
