
export default {

  FETCH_ALL_LABELS: 'FETCH_ALL_LABELS',
  CREATE_LABEL: 'CREATE_LABEL',
  UPDATE_LABEL: 'UPDATE_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',
  
  SET_PERIOD: 'SET_PERIOD',
  SET_DATE_RANGE: 'SET_DATE_RANGE',
  PARTITION_PERIOD: 'PARTITION_PERIOD',

  CREATE_OPERATION: 'CREATE_OPERATION',
  UPDATE_OPERATION: 'UPDATE_OPERATION',
  DELETE_OPERATION: 'DELETE_OPERATION',
  SELECT_OPERATION: 'SELECT_OPERATION',
  UPDATE_OPERATIONS_SET_LABEL: 'UPDATE_OPERATIONS_SET_LABEL',
  
  NOTIFY: 'NOTIFY',

  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',

};
