
export const Actions = {

  // Dialog Actions
  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',

  // Label Actions
  FETCH_ALL_LABELS: 'FETCH_ALL_LABELS',
  CREATE_LABEL: 'CREATE_LABEL',
  UPDATE_LABEL: 'UPDATE_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',

  // Notification Actions
  NOTIFY: 'NOTIFY',
  
  // Operation Actions
  FETCH_ALL_OPERATIONS: 'FETCH_ALL_OPERATIONS',
  FETCH_OPERATIONS_GROUPED_BY_MONTH: 'FETCH_OPERATIONS_GROUPED_BY_MONTH',
  SET_OPERATIONS: 'SET_OPERATIONS',
  CREATE_OPERATION: 'CREATE_OPERATION',
  UPDATE_OPERATION: 'UPDATE_OPERATION',
  DELETE_OPERATION: 'DELETE_OPERATION',

};
